version: '2.1'
volumes:
  settings:
services:
  browser:
    restart: always
    image: bh.cr/balenalabs/browser-aarch64/2.9.0
    privileged: true
    volumes:
      - 'settings:/data'
  mojo:
    restart: always
    build: ./mojo-demo
    ports:
      - "8080:8080"